### PR TITLE
Fwji ocp 42 refresh

### PR DESCRIPTION
**Pull request by fwji**
Updating the contents for OCP 4.2 EFK deployments

### CODE REVIEW

**Comment by fwji** [comment]
Preview of the published guide can be visited here http://rhel7-openshift.rtp.raleigh.ibm.com:4000/guides/app-logging/#install-cluster-logging

**Review by nateziemann — CHANGES_REQUESTED** [review]
So I spoke w/ Don this morning.   Here's what I'd like to do w/ this guide.
1.  Separate it from the current Kabanero/OKD 3.11 guide.  Retain both for some period of time.
2.  Create this new guide explicitly tested against Kab 0.3.0rc-1 and OCP 4.2 (matching what shipped with  CP4Apps  4.0.  Title it similar to existing guide but change OKD to OCP.  In guide use OCP 4.2 instead  of references to OKD, and spell out OCP on first use.  
3.  Once Red Hat provides us an OKD 4.x stream, we must update this new guide removing all mention of OCP and replacing it w/ OKD and a later version of Kabanero, providing our intended long term positioning of an full open stack top to bottom (OKD for  container platform, Kabanero for cloud-native governance with Application Stacks and Pipelines).

For more questions, contact Don and Nate.

**Comment by fwji** [comment]
Thanks for the input Nate @nateziemann, will be working on the requested changes

**Comment by donbourne** [comment]
This PR is being replaced by https://github.com/kabanero-io/draft-guide-app-logging-ocp4.2/pull/1  (since we want this RHOCP 4.2 content to be a new guide rather than replace this guide).  @fwji , can you please close this one?

**Pull request closed without merging**
